### ISSUE TITLE
Can't compile rustler 

### ISSUE THREAD

**Issue by sschneider1207** [hansihe/Rustler#27]
One of the dependencies of `rustler_codegen`, `synthax`, is failing to compile for me with the following error:
```
   Compiling synthax v0.3.2
error: no associated item named `SpecialVarNt` found for type `syntax::parse::token::Token` in the current scope
   --> /home/name/.cargo/registry/src/github.com-1ecc6299db9ec823/synthax-0.3.2/src/expr.rs:172:13
    |
172 |             Token::SpecialVarNt(_) |
    |             ^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `synthax`.
```

I've tried compiling it with the following versions:
* stable - rustc 1.12.1 (d4f39402a 2016-10-19)
* nightly - rustc 1.14.0-nightly (7c69b0d5a 2016-11-01)

**Comment by evanmcc** [comment]
same.  Tried backing off a version or two and going to nightly, but no luck.

**Comment by scrogson** [comment]
Same here.

**Comment by hansihe** [comment]
The error is fixed in git.

Because the fix removed a few features, I have been reluctant about making a new release before reimplementing them properly. I guess having a working release is more important than preventing regressions, and I should probably make a new release.

**Comment by scrogson** [comment]
I just fixed a few issues with compilation in #30 (which has been merged).

You'll need to use master for all dependencies until the next release.

```ex
# mix.exs
defp deps do
  [{:rustler, github: "hansihe/rustler", sparse: "rustler_mix"}]
end
```

```toml
# Cargo.toml
[build-dependencies]
rustler_codegen = { git = "https://github.com/hansihe/Rustler" }

[dependencies]
rustler = { git = "https://github.com/hansihe/Rustler" }
rustler_codegen = { git = "https://github.com/hansihe/Rustler" }
```

Finally, you'll need to use the following in your Elixir module:

```ex
...

require Rustler # to get access to the `load_nif/2` macro

def load_nif do
  # args:
  # * your OTP application name
  # * your rust crate name
  :ok = Ruster.load_nif(:my_app, "my_app")
end

...
```

```
λ rustc -V
rustc 1.15.0-nightly (43006fcea 2016-11-15)
```

Hope that helps!
